# Problem Statement: **Welcome to AI Town!**

### You’ve been hired as an AI engineer in **AI Town**, a futuristic city powered by artificial intelligence. Your job is to use PyTorch to solve foundational challenges that AI Town faces. Each task requires you to demonstrate your expertise with PyTorch basics.



---



Imports and CUDA

In [1]:
import torch

# Check if CUDA (GPU) is available
device = torch.device('cuda' if torch.cuda.is_available() else 'mps')
print(f"Using device: {device}")


Using device: mps




---



**Task1: Inventory Management**

AI Town’s warehouse uses sensors to record the inventory of 5 items every day. Each day’s data is represented as a list of integers (number of units).

In [5]:
#1 Create a PyTorch Tensor from the following inventory data
inventory = [[12, 15, 10, 0, 5],
             [10, 8, 7, 5, 4],
             [20, 10, 15, 5, 2]]
inventory_data = torch.tensor(inventory, dtype=torch.float16)

In [6]:
#2 Find the total inventory for each item across all days
total_inventory = inventory_data.sum(dim=0)
total_inventory

tensor([42., 33., 32., 10., 11.], dtype=torch.float16)

In [7]:
#3 Find the average inventory per day
avg_inventory = inventory_data.mean(dim=1)
avg_inventory

tensor([ 8.3984,  6.8008, 10.3984], dtype=torch.float16)



---



**Task2: Monitoring Vehicle Flow**

AI Town uses a sensor to monitor the number of vehicles passing through two main roads every hour. The data for one day (24 hours) is represented as two
1×24 tensors.

In [11]:
#1 Simulate this data using PyTorch's Random Functions
road1 = torch.randint(50, 200, (24,))
road2 = torch.randint(50, 200, (24,))
print(road1)
print(road2)

tensor([160, 151, 118,  52, 162,  60,  91,  59, 108, 175,  57, 147, 137, 196,
         50, 108, 115, 171,  74,  65, 100,  60, 156, 121])
tensor([112,  68,  97,  75,  77,  84, 112,  59, 189, 116, 138, 122, 138,  94,
        150, 162,  85,  84,  66, 104, 120, 177, 143, 155])


In [15]:
#2 Write the function to calculate the total vehicle flow for each road across the entire day
from torch import Tensor
def calculate_cars(road: Tensor):
    return road.sum(dim=0)

road1_total = calculate_cars(road1)
road1_total

tensor(2693)

In [16]:
#3 Write the function to calculate the total vehicle flow for each hour across both roads
def calculate_cars_per_hour(road1: Tensor, road2: Tensor):
    return road1 + road2

total_car_per_hour = calculate_cars_per_hour(road1, road2)
total_car_per_hour

tensor([272, 219, 215, 127, 239, 144, 203, 118, 297, 291, 195, 269, 275, 290,
        200, 270, 200, 255, 140, 169, 220, 237, 299, 276])



---



**Task3: Fitness Matrix**

The AI Gym tracks members’ fitness scores using a 3×3 matrix for *strength*, *stamina*, and f*lexibility*. Each row represents a different member, and each column represents a specific metric.

In [23]:
#1 Create a 3*3 tensor matrix and multiply the scores of each member by a weight factor: [0.8, 1.2, 1.5]
fitness_data = torch.randint(10, 50, (3, 3))
weights = torch.tensor([0.8, 1.2, 1.5])
weighted_fitness = weights * fitness_data
weighted_fitness

tensor([[11.2000, 48.0000, 34.5000],
        [28.0000, 21.6000, 18.0000],
        [24.8000, 46.8000, 72.0000]])

In [25]:
fitness_data

tensor([[14, 40, 23],
        [35, 18, 12],
        [31, 39, 48]])

In [26]:
#2 Find the row-wise and column-wise maximum scores
#2 Find the row-wise and column-wise maximum scores
row_max = weighted_fitness.max(dim=1) # max for each row
col_max = weighted_fitness.max(dim=0) # max for each column
print(row_max)
print(col_max)

torch.return_types.max(
values=tensor([48., 28., 72.]),
indices=tensor([1, 0, 2]))
torch.return_types.max(
values=tensor([28., 48., 72.]),
indices=tensor([1, 0, 2]))


In [27]:
#3 Transpose the fitness matrix and interpret it's new structure (shape)
fitness_data.t()

tensor([[14, 35, 31],
        [40, 18, 39],
        [23, 12, 48]])



---



**Task4: Chain Rule in Action**

AI Lab is running experiments to understand the effect of temperature (
x) on a chemical reaction rate (y). The relationship is given as:
$y = 2x^3 + 5x^2 - 3x + 7$



In [31]:
#1 Use PyTorch to compute 'y' for x = 4
x = torch.tensor(4, requires_grad=True, dtype=torch.float16)
y =   2*x**3 + 5*x**2 - 3*x + 7

y

tensor(203., dtype=torch.float16, grad_fn=<AddBackward0>)

In [32]:
#2 Calculate dy/dx(gradient) using PyTorch's autograd
y.backward()
gradient = x.grad
gradient

tensor(133., dtype=torch.float16)



---



**Task5: Camera Calibration**

AI Town’s surveillance cameras need to align their focus. You are given the following matrices for two cameras’ focus adjustments:

In [34]:
'''
camera1 = torch.tensor([[1, 2], [3, 4]])
camera2 = torch.tensor([[5, 6], [7, 8]])
'''

camera1 = torch.tensor([[1, 2], [3, 4]])
camera2 = torch.tensor([[5, 6], [7, 8]])

In [35]:
#1 Perform an element-wise multiplication of matrices ( Hadamard Product)
product = camera1 * camera2
product

tensor([[ 5, 12],
        [21, 32]])

In [36]:
#2 Compute Dot Product of the two matrices
torch.matmul(camera1, camera2)

tensor([[19, 22],
        [43, 50]])

In [37]:
#3 Compute the Determinant of each matrix
#3 Compute the Determinant of each matrix
det_camera1 = torch.det(camera1.float())
det_camera2 = torch.det(camera2.float())
print(det_camera1)
print(det_camera2)

tensor(-2.)
tensor(-2.0000)




---



**Task6: Neural Network Foundations**

Our AI University uses simplified single neuron model (perceptron):
$$y = wx + b$$

In [38]:
#1 Create tensors for w  = 2, b = 1, x = [1, 2, 3, 4]
w= torch.tensor(2, requires_grad=True, dtype=torch.float16)
b= torch.tensor(1, requires_grad=True, dtype=torch.float16)
x = torch.tensor([1, 2, 3, 4], requires_grad=True, dtype=torch.float16)



In [40]:
#2 Compute tensors for y
y = w * x + b 
y

tensor([3., 5., 7., 9.], dtype=torch.float16, grad_fn=<AddBackward0>)



---

